### PR TITLE
Added python/psi4numpy implementation of CQED-RHF

### PR DESCRIPTION
**Pull request by FoleyLab**
@edeprince3 there is a plain python version and one in a Jupyter notebook with the key equations for the self polarization term of the Hamiltonian and the modified Fock operator included.  I abandoned trying to modify the C++ version since I (a) don't understand the psi4 machinery / flow well enough to do it quickly, and (b) can't compile it to test it anyway!

### CODE REVIEW

**Comment by edeprince3** [comment]
@FoleyLab I will try to review this PR this week.

**Comment by FoleyLab** [comment]
Apropos of nothing I just realized there is a GitHub app for iPhone and now everyone's life will become a bit more miserable

**Comment by edeprince3** [comment]
Only if I install it.

**Comment by edeprince3** [comment]
by the way, I just added an issue related to non-z-polarized modes since you reminded me of this problem

**Comment by FoleyLab** [comment]
In the code I attached, I compute <\mu> once in the "ordinary" RHF basis and then treated it as a constant thereafter.
However, revisiting the CIS equations, it seems that having <\mu> computed in the CQED-RHF basis would be advantageous, since then terms like <0| HF | \lambda \cdot (\hat{\mu} - <\mu> ) (b^\dagger + b) | HF > 1 >  would be zero.  

I'm wondering if I should actually update <\mu> in the CQED-RHF iterations then?

**Comment by FoleyLab** [comment]
@edeprince3 related to my previous comment, I made a few updates to this PR

  - cqed_rhf is now a function in a new python file called helper_cqed_rhf.py so it can be more easily called and passed a string specifying the molecule, a vector for the electric field
  - the cqed_rhf function also takes an optional argument specifying whether or not the dipole moment expectation value <mu> should be updated at each SCF step.  If True (default), then <mu> will end up being in the CQED_RHF basis.  If False, <mu> will stay in the canonical RHF basis throughout.

**Comment by FoleyLab** [comment]
Also maybe you can send me the bond lengths and total QED RHF energies for the NaX series you reported the EAs for in the JCP and I can update this PR with a few tests using them

**Comment by FoleyLab** [comment]
@edeprince3 this pull request has been updated in the following ways:

- cqed_rhf method is now implemented as a callable python function in helper_cqed_rhf.py that returns a dictionary with a number of quantities, including the ordinary rhf energy, the cqed-rhf energy, dipole moment expectation values, transformation vectors, among other things
- cs_cqed_cis is the cqed_cis method in the coherent state basis, also implemented in a callable python function in helper_cs_cqed_cis.py.  It will run cqed-rhf first, then use the MOs to transform all quantities for the cqed-cis equations.  
- validate_cqed_rhf.ipynb tests heper_cqed_rhf.py against results you provided for NaF and NaCl, and also performs the bond stretch of MgH+ for a few different values of the electric field
- mgh_exploration.ipynb performs tests against cs_cqed_cis and psi4s cis in the limit that omega=0 and lambda=(0,0,0) and also looks at the polaritonic states of MgH+ compared to the ground (X) and first-excited singlet (A) states as computed by CIS.  It also compares to a model Pauli-Fierz Hamiltonian that uses the CIS energies, transition dipoles, and dipole moments.  Because psi4 does not compute total dipole moments for CIS excited states (to my knowledge), I have another callable python function (helper_cis.py) that computes the CIS energies, transition dipole moments, and total dipole moments for this purpose.  It is also validated against psi4's cis energies in the first few cells of the mgh_exploration.ipynb notebook

**Comment by edeprince3** [comment]
I think this looks good. @FoleyLab can you make one change? Move src/psi4numpy_polaritonic_scf to src/psi4numpy/polaritonic_scf? I'm

**Pull request merged**
